CREATE DATABASE SoftUni

CREATE TABLE Towns (
	Id INT IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,

	CONSTRAINT PK_Towns
	PRIMARY KEY(Id)
)

CREATE TABLE Addresses (
	Id INT IDENTITY,
	AddressText NVARCHAR(50) NOT NULL,
	TownId INT CONSTRAINT FK_Addresses_Towns FOREIGN KEY REFERENCES Towns(Id) NOT NULL,

	CONSTRAINT PK_Addresses
	PRIMARY KEY(Id)
)

CREATE TABLE Departments (
	Id INT IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,

	CONSTRAINT PK_Departments
	PRIMARY KEY(Id)
)

CREATE TABLE Employees (
	Id INT IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	JobTitle NVARCHAR(50) NOT NULL,
	DepartmentId INT CONSTRAINT FK_Employees_Departments FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
	HireDate DATE NOT NULL,
	Salary DECIMAL(15, 2) NOT NULL,
	AddressId INT CONSTRAINT FK_Employees_Addresses FOREIGN KEY REFERENCES Addresses(Id),

	CONSTRAINT PK_Employees
	PRIMARY KEY(Id),
)